### ISSUE TITLE
how to use this mod?

### ISSUE THREAD

**Issue by Twotoolus-FLY-LShst** [SwiftCobra/SpeedLimitMod#1]
![how](https://github.com/SwiftCobra/SpeedLimitMod/assets/23209374/6d1d9037-a3a4-491c-8d2e-653d463e38cb)

i try upgrade tool or build road. but noting change.

i used BepInEx 5.4.21(because, Thunderstore have 5.4.21 version. not 5.4.22)
anyidea?

if only work 6 version, please upload 5 version too.

**Comment by SwiftCobra** [comment]
Did you figure out how to use the mod?

I am going to add instructions in the next release.

**Comment by Twotoolus-FLY-LShst** [comment]
yes. my friend say, click to road name. and work. =D
